dist: xenial
language: python
python:
  - "3.7"
  - "3.8"
services:
  - postgresql
env:
  - SECRET_KEY=test-secret USER_EMAIL=test@example.com
before_install:
  - export TZ=Europe/Moscow
  - nvm install 12
  - nvm use 12
install:
  - pip install poetry
  - poetry install
  - inv build.dirs
  - inv build.frontend --no-rebuild
before_script:
  - psql -c "CREATE USER airy WITH password 'airy' CREATEDB;" -U postgres
script:
  - inv check.py-style
  - inv check.py-unit --no-debug
  - inv check.frontend
