language: python
python:
  - "3.5"
  - "3.6"
services:
  - postgresql
env:
  - SECRET_KEY=test USER_EMAIL=test@example.com
before_install:
  - export TZ=Europe/Moscow
  - nvm install 8.0
  - nvm use 8.0
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv run inv build.dirs
  - pipenv run inv build.frontend --no-rebuild
before_script:
  - psql -c "CREATE USER airy WITH password 'airy' CREATEDB;" -U postgres
script:
  - pipenv run flake8 --max-complexity=8 fabfile
  - pipenv run flake8 --max-complexity=10 airy
  - pipenv run flake8 --max-complexity=8 alembic/env.py
  - pipenv run safety check --bare
  - pipenv run bandit -c bandit.yaml -r airy
  - pipenv run pytest airy/tests
  - "npm run grunt check:js check:css check:html"
