"""Added time entries

Revision ID: 1b4772e1f9f
Revises: 58973c4a356
Create Date: 2014-04-20 20:06:43.477038

"""

# revision identifiers, used by Alembic.
revision = '1b4772e1f9f'
down_revision = '58973c4a356'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('times_entries')
    ### end Alembic commands ###
