"""Add table 'reports'

Revision ID: 28b17a6c5cf
Revises: 1b4772e1f9f
Create Date: 2014-06-08 12:15:24.712148

"""

# revision identifiers, used by Alembic.
revision = '28b17a6c5cf'
down_revision = '1b4772e1f9f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_time', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###
