"""Add tasks

Revision ID: 58973c4a356
Revises: 25b6970745c
Create Date: 2014-04-18 14:28:49.641451

"""

# revision identifiers, used by Alembic.
revision = '58973c4a356'
down_revision = '25b6970745c'

from alembic import op
import sqlalchemy as sa


status = sa.Enum('open', 'completed', 'closed', name='status')


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', status, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    status.drop(op.get_bind())
    ### end Alembic commands ###
