"""Remove 'completed' task status

Revision ID: 46be3ad7383
Revises: 3972b73167
Create Date: 2015-03-29 22:50:50.390303

"""

# revision identifiers, used by Alembic.
revision = '46be3ad7383'
down_revision = '3972b73167'

from sqlalchemy.sql import table, column
from alembic import op
import sqlalchemy as sa


def upgrade():
    tasks = table('tasks', column('status', sa.String))
    op.execute(
        tasks.update().\
            where(tasks.c.status == op.inline_literal('completed')).\
            values({'status': op.inline_literal('closed')})
    )

    

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
