"""Remove report model

Revision ID: 3972b73167
Revises: 27ba8807426
Create Date: 2015-03-29 22:12:56.720361

"""

# revision identifiers, used by Alembic.
revision = '3972b73167'
down_revision = '27ba8807426'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('total_time', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='reports_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='reports_pkey')
    )
    ### end Alembic commands ###
