"""Add duration field to TimeEntry model

Revision ID: 53979be7153
Revises: 46be3ad7383
Create Date: 2015-07-11 14:56:04.495292

"""

# revision identifiers, used by Alembic.
revision = '53979be7153'
down_revision = '46be3ad7383'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_entries', sa.Column('duration', sa.Interval(), nullable=True))
    op.alter_column('time_entries', 'amount',
        existing_type=sa.NUMERIC(precision=4, scale=2),
        nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'duration')
    op.alter_column('time_entries', 'amount',
        existing_type=sa.NUMERIC(precision=4, scale=2),
        nullable=False)
    ### end Alembic commands ###
