"""add_url_field_to_task

Revision ID: 3ac6300917e0
Revises: 2d89bdc3fcd
Create Date: 2017-02-22 11:24:19.670228

"""

# revision identifiers, used by Alembic.
revision = '3ac6300917e0'
down_revision = '2d89bdc3fcd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'url')
    # ### end Alembic commands ###
